Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,134 +14,134 @@ env:
   CARGO_TERM_COLOR: always
 
 jobs:
-  lint:
-    runs-on: ubuntu-22.04
+  # lint:
+  #   runs-on: ubuntu-22.04
 
-    steps:
-      - uses: actions/checkout@v3
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - uses: dtolnay/rust-toolchain@master
-        with:
-          toolchain: nightly
-          components: rustfmt, clippy, miri, rust-src
+  #     - uses: dtolnay/rust-toolchain@master
+  #       with:
+  #         toolchain: nightly
+  #         components: rustfmt, clippy, miri, rust-src
 
-      - uses: Swatinem/rust-cache@v2
+  #     - uses: Swatinem/rust-cache@v2
 
-      - uses: taiki-e/install-action@v2
-        with:
-          tool: cargo-hack,taplo-cli
+  #     - uses: taiki-e/install-action@v2
+  #       with:
+  #         tool: cargo-hack,taplo-cli
 
-      - name: Check C formatting
-        run: git ls-files -- '*.c' '*.h' | xargs clang-format --dry-run --Werror
+  #     - name: Check C formatting
+  #       run: git ls-files -- '*.c' '*.h' | xargs clang-format --dry-run --Werror
 
-      - run: taplo fmt --check
+  #     - run: taplo fmt --check
 
-      - name: Check formatting
-        run: cargo fmt --all -- --check
+  #     - name: Check formatting
+  #       run: cargo fmt --all -- --check
 
-      - name: Run clippy
-        run: cargo hack clippy --all-targets --feature-powerset --workspace -- --deny warnings
+  #     - name: Run clippy
+  #       run: cargo hack clippy --all-targets --feature-powerset --workspace -- --deny warnings
 
-      - name: Check public API
-        run: cargo xtask public-api
+  #     - name: Check public API
+  #       run: cargo xtask public-api
 
-      - name: Run miri
-        run: |
-          set -euxo pipefail
-          cargo hack miri test --all-targets --feature-powerset \
-            --exclude aya-bpf \
-            --exclude aya-bpf-bindings \
-            --exclude aya-log-ebpf \
-            --exclude integration-ebpf \
-            --exclude integration-test \
-            --workspace
+  #     - name: Run miri
+  #       run: |
+  #         set -euxo pipefail
+  #         cargo hack miri test --all-targets --feature-powerset \
+  #           --exclude aya-bpf \
+  #           --exclude aya-bpf-bindings \
+  #           --exclude aya-log-ebpf \
+  #           --exclude integration-ebpf \
+  #           --exclude integration-test \
+  #           --workspace
 
-  build-test-aya:
-    strategy:
-      fail-fast: false
-      matrix:
-        arch:
-          - x86_64-unknown-linux-gnu
-          - aarch64-unknown-linux-gnu
-          - armv7-unknown-linux-gnueabi
-          - riscv64gc-unknown-linux-gnu
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v3
+  # build-test-aya:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch:
+  #         - x86_64-unknown-linux-gnu
+  #         - aarch64-unknown-linux-gnu
+  #         - armv7-unknown-linux-gnueabi
+  #         - riscv64gc-unknown-linux-gnu
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - uses: dtolnay/rust-toolchain@master
-        with:
-          toolchain: stable
-          targets: ${{ matrix.arch }}
+  #     - uses: dtolnay/rust-toolchain@master
+  #       with:
+  #         toolchain: stable
+  #         targets: ${{ matrix.arch }}
 
-      - uses: Swatinem/rust-cache@v2
+  #     - uses: Swatinem/rust-cache@v2
 
-      - uses: taiki-e/install-action@cargo-hack
+  #     - uses: taiki-e/install-action@cargo-hack
 
-      - uses: taiki-e/setup-cross-toolchain-action@v1
-        with:
-          target: ${{ matrix.arch }}
+  #     - uses: taiki-e/setup-cross-toolchain-action@v1
+  #       with:
+  #         target: ${{ matrix.arch }}
 
-      - name: Build
-        run: |
-          set -euxo pipefail
-          cargo hack build --all-targets --feature-powerset \
-            --exclude aya-bpf \
-            --exclude aya-bpf-bindings \
-            --exclude aya-log-ebpf \
-            --exclude integration-ebpf \
-            --workspace
+  #     - name: Build
+  #       run: |
+  #         set -euxo pipefail
+  #         cargo hack build --all-targets --feature-powerset \
+  #           --exclude aya-bpf \
+  #           --exclude aya-bpf-bindings \
+  #           --exclude aya-log-ebpf \
+  #           --exclude integration-ebpf \
+  #           --workspace
 
-      - name: Test
-        env:
-          RUST_BACKTRACE: full
-        run: |
-          set -euxo pipefail
-          cargo hack test --all-targets --feature-powerset \
-            --exclude aya-bpf \
-            --exclude aya-bpf-bindings \
-            --exclude aya-log-ebpf \
-            --exclude integration-ebpf \
-            --exclude integration-test \
-            --workspace
+  #     - name: Test
+  #       env:
+  #         RUST_BACKTRACE: full
+  #       run: |
+  #         set -euxo pipefail
+  #         cargo hack test --all-targets --feature-powerset \
+  #           --exclude aya-bpf \
+  #           --exclude aya-bpf-bindings \
+  #           --exclude aya-log-ebpf \
+  #           --exclude integration-ebpf \
+  #           --exclude integration-test \
+  #           --workspace
 
-  build-test-aya-bpf:
-    strategy:
-      fail-fast: false
-      matrix:
-        arch:
-          - x86_64
-          - aarch64
-          - arm
-          - riscv64
-        target:
-          - bpfel-unknown-none
-          - bpfeb-unknown-none
-    runs-on: ubuntu-22.04
+  # build-test-aya-bpf:
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       arch:
+  #         - x86_64
+  #         - aarch64
+  #         - arm
+  #         - riscv64
+  #       target:
+  #         - bpfel-unknown-none
+  #         - bpfeb-unknown-none
+  #   runs-on: ubuntu-22.04
 
-    steps:
-      - uses: actions/checkout@v3
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - uses: dtolnay/rust-toolchain@master
-        with:
-          toolchain: nightly
-          components: rust-src
+  #     - uses: dtolnay/rust-toolchain@master
+  #       with:
+  #         toolchain: nightly
+  #         components: rust-src
 
-      - uses: Swatinem/rust-cache@v2
+  #     - uses: Swatinem/rust-cache@v2
 
-      - name: bpf-linker
-        run: cargo install bpf-linker --git https://github.com/aya-rs/bpf-linker.git
+  #     - name: bpf-linker
+  #       run: cargo install bpf-linker --git https://github.com/aya-rs/bpf-linker.git
 
-      - uses: taiki-e/install-action@cargo-hack
-      - name: Build
-        env:
-          CARGO_CFG_BPF_TARGET_ARCH: ${{ matrix.arch }}
-        run: |
-          set -euxo pipefail
-          cargo hack build --package aya-bpf --package aya-log-ebpf \
-            --feature-powerset \
-            --target ${{ matrix.target }} \
-            -Z build-std=core
+  #     - uses: taiki-e/install-action@cargo-hack
+  #     - name: Build
+  #       env:
+  #         CARGO_CFG_BPF_TARGET_ARCH: ${{ matrix.arch }}
+  #       run: |
+  #         set -euxo pipefail
+  #         cargo hack build --package aya-bpf --package aya-log-ebpf \
+  #           --feature-powerset \
+  #           --target ${{ matrix.target }} \
+  #           -Z build-std=core
 
   run-integration-test:
     strategy:
@@ -196,6 +196,9 @@ jobs:
           set -euxo pipefail
           brew install findutils qemu dpkg pkg-config llvm
           echo /usr/local/opt/llvm/bin >> $GITHUB_PATH
+
+          brew tap-new $USER/local-qemu
+          brew extract --version=8.0.3 qemu $USER/local-qemu
           brew install qemu@8.0.3
 
       - name: bpf-linker
